# Generated by Django 4.0.2 on 2022-02-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addExists', models.BooleanField()),
                ('rangeAddNum12', models.IntegerField()),
                ('rangeAddNum21', models.IntegerField()),
                ('rangeAddNum11', models.IntegerField()),
                ('rangeAddNum22', models.IntegerField()),
                ('mulsExists', models.BooleanField()),
                ('rangeMulNum12', models.IntegerField()),
                ('rangeMulNum21', models.IntegerField()),
                ('rangeMulNum11', models.IntegerField()),
                ('rangeMulNum22', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
