# Generated by Django 4.0.2 on 2022-02-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetic_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionslist',
            name='rangeAddNum11',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeAddNum12',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeAddNum21',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeAddNum22',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeMulNum11',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeMulNum12',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeMulNum21',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questionslist',
            name='rangeMulNum22',
            field=models.IntegerField(null=True),
        ),
    ]
