# Generated by Django 4.0.2 on 2022-03-03 02:51

import arithmetic_game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetic_game', '0002_alter_questionslist_rangeaddnum11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addExists', models.BooleanField()),
                ('rangeAddNum11', models.IntegerField(null=True)),
                ('rangeAddNum12', models.IntegerField(null=True)),
                ('rangeAddNum21', models.IntegerField(null=True)),
                ('rangeAddNum22', models.IntegerField(null=True)),
                ('mulsExists', models.BooleanField()),
                ('rangeMulNum11', models.IntegerField(null=True)),
                ('rangeMulNum12', models.IntegerField(null=True)),
                ('rangeMulNum21', models.IntegerField(null=True)),
                ('rangeMulNum22', models.IntegerField(null=True)),
                ('duration', models.IntegerField()),
                ('questions', models.JSONField(verbose_name={'duration': models.IntegerField(), 'questions': arithmetic_game.models.QuestionSet.QBuilder})),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionsList',
        ),
    ]
